window.Modernizr=function(i,e,m){function t(a,b){return typeof a===b}function H(a,b){for(var c in a)if(j[a[c]]!==m&&(!b||b(a[c],u)))return!0}function r(a,b){var c=a.charAt(0).toUpperCase()+a.substr(1),c=(a+" "+w.join(c+" ")+c).split(" ");return!!H(c,b)}function I(){h.input=function(a){for(var b=0,c=a.length;b<c;b++)L[a[b]]=!!(a[b]in g);return L}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));h.inputtypes=function(a){for(var b=0,c,f,k=a.length;b<k;b++){g.setAttribute("type",
f=a[b]);if(c=g.type!=="text")g.value=x,g.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(f)&&g.style.WebkitAppearance!==m?(n.appendChild(g),c=e.defaultView,c=c.getComputedStyle&&c.getComputedStyle(g,null).WebkitAppearance!=="textfield"&&g.offsetHeight!==0,n.removeChild(g)):/^(search|tel)$/.test(f)||(/^(url|email)$/.test(f)?c=g.checkValidity&&g.checkValidity()===!1:/^color$/.test(f)?(n.appendChild(g),c=g.value!=x,n.removeChild(g)):c=g.value!=x);D[a[b]]=!!c}return D}("search tel url email datetime date month week time datetime-local number range color".split(" "))}
var h={},n=e.documentElement,p=e.head||e.getElementsByTagName("head")[0],u=e.createElement("modernizr"),j=u.style,g=e.createElement("input"),x=":)",s=Object.prototype.toString,o=" -webkit- -moz- -o- -ms- -khtml- ".split(" "),w="Webkit Moz O ms Khtml".split(" "),d={},D={},L={},E=[],F,y=e.getElementsByTagName("script")[0],J=function(){var a={},b=e.createElement("body"),c=e.createElement("div");c.id="modernizr-mqtest";b.appendChild(c);return function(f){if(a[f]==m){if(i.matchMedia)return a[f]=matchMedia(f).matches;
var k=e.createElement("style"),d="@media "+f+" { #modernizr-mqtest { position: absolute; } }";k.type="text/css";k.styleSheet?k.styleSheet.cssText=d:k.appendChild(e.createTextNode(d));y.parentNode.insertBefore(b,y);y.parentNode.insertBefore(k,y);a[f]=(i.getComputedStyle?getComputedStyle(c,null):c.currentStyle).position=="absolute";b.parentNode.removeChild(b);k.parentNode.removeChild(k)}return a[f]}}(),z=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",
abort:"img"};return function(b,c){var c=c||e.createElement(a[b]||"div"),b="on"+b,f=b in c;f||(c.setAttribute||(c=e.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(b,""),f=t(c[b],"function"),t(c[b],m)||(c[b]=m),c.removeAttribute(b)));return f}}(),v={}.hasOwnProperty,G;G=!t(v,m)&&!t(v.call,m)?function(a,b){return v.call(a,b)}:function(a,b){return b in a&&t(a.constructor.prototype[b],m)};d.flexbox=function(){var a=e.createElement("div"),b=e.createElement("div");(function(a,b,
c,d){b+=":";a.style.cssText=(b+o.join(c+";"+b)).slice(0,-b.length)+(d||"")})(a,"display","box","width:42px;padding:0;");b.style.cssText=o.join("box-flex:1;")+"width:10px;";a.appendChild(b);n.appendChild(a);var c=b.offsetWidth===42;a.removeChild(b);n.removeChild(a);return c};d.canvas=function(){var a=e.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))};d.canvastext=function(){return!(!h.canvas||!t(e.createElement("canvas").getContext("2d").fillText,"function"))};d.webgl=function(){return!!i.WebGLRenderingContext};
d.touch=function(){return"ontouchstart"in i||J("("+o.join("touch-enabled),(")+"modernizr)")};d.geolocation=function(){return!!navigator.geolocation};d.postmessage=function(){return!!i.postMessage};d.websqldatabase=function(){return!!i.openDatabase};d.indexedDB=function(){for(var a=-1,b=w.length;++a<b;)if(i[w[a].toLowerCase()+"IndexedDB"])return!0;return!!i.indexedDB};d.hashchange=function(){return z("hashchange",i)&&(e.documentMode===m||e.documentMode>7)};d.history=function(){return!(!i.history||
!history.pushState)};d.draganddrop=function(){return z("dragstart")&&z("drop")};d.websockets=function(){return"WebSocket"in i};d.rgba=function(){j.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+j.backgroundColor).indexOf("rgba")};d.hsla=function(){j.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+j.backgroundColor).indexOf("rgba")||!!~(""+j.backgroundColor).indexOf("hsla")};d.multiplebgs=function(){j.cssText="background:url(//:),url(//:),red url(//:)";return/(url\s*\(.*?){3}/.test(j.background)};
d.backgroundsize=function(){return r("backgroundSize")};d.borderimage=function(){return r("borderImage")};d.borderradius=function(){return r("borderRadius","",function(a){return!!~(""+a).indexOf("orderRadius")})};d.boxshadow=function(){return r("boxShadow")};d.textshadow=function(){return e.createElement("div").style.textShadow===""};d.opacity=function(){var a=o.join("opacity:.55;")+"";j.cssText=a;return/^0.55$/.test(j.opacity)};d.cssanimations=function(){return r("animationName")};d.csscolumns=function(){return r("columnCount")};
d.cssgradients=function(){var a=("background-image:"+o.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+o.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);j.cssText=a;return!!~(""+j.backgroundImage).indexOf("gradient")};d.cssreflections=function(){return r("boxReflect")};d.csstransforms=function(){return!!H(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};d.csstransforms3d=function(){var a=!!H(["perspectiveProperty",
"WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);a&&"webkitPerspective"in n.style&&(a=J("("+o.join("transform-3d),(")+"modernizr)"));return a};d.csstransitions=function(){return r("transitionProperty")};d.fontface=function(){var a,b,c=p||n,f=e.createElement("style");b=e.implementation||{hasFeature:function(){return!1}};f.type="text/css";c.insertBefore(f,c.firstChild);a=f.sheet||f.styleSheet;b=(b.hasFeature("CSS2","")?function(b){if(!a||!b)return!1;var f=!1;try{a.insertRule(b,
0),f=/src/i.test(a.cssRules[0].cssText),a.deleteRule(a.cssRules.length-1)}catch(c){}return f}:function(b){if(!a||!b)return!1;a.cssText=b;return a.cssText.length!==0&&/src/i.test(a.cssText)&&a.cssText.replace(/\r+|\n+/g,"").indexOf(b.split(" ")[0])===0})('@font-face { font-family: "font"; src: url("//:"); }');c.removeChild(f);return b};d.video=function(){var a=e.createElement("video"),b=!!a.canPlayType;if(b)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"'),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"')||
a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"'),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"');return b};d.audio=function(){var a=e.createElement("audio"),b=!!a.canPlayType;if(b)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"'),b.mp3=a.canPlayType("audio/mpeg;"),b.wav=a.canPlayType('audio/wav; codecs="1"'),b.m4a=a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;");return b};d.localstorage=function(){try{return!!localStorage.getItem}catch(a){return!1}};
d.sessionstorage=function(){try{return!!sessionStorage.getItem}catch(a){return!1}};d.webWorkers=function(){return!!i.Worker};d.applicationcache=function(){return!!i.applicationCache};d.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};d.inlinesvg=function(){var a=e.createElement("div");a.innerHTML="<svg/>";return(a.firstChild&&a.firstChild.namespaceURI)=="http://www.w3.org/2000/svg"};d.smil=function(){return!!e.createElementNS&&/SVG/.test(s.call(e.createElementNS("http://www.w3.org/2000/svg",
"animate")))};d.svgclippaths=function(){return!!e.createElementNS&&/SVG/.test(s.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var A in d)G(d,A)&&(F=A.toLowerCase(),h[F]=d[A](),E.push((h[F]?"":"no-")+F));h.input||I();h.crosswindowmessaging=h.postmessage;h.historymanagement=h.history;h.addTest=function(a,b){a=a.toLowerCase();if(!h[a])return b=!!b(),n.className+=" "+(b?"":"no-")+a,h[a]=b,h};j.cssText="";u=g=null;i.attachEvent&&function(){var a=e.createElement("div");a.innerHTML=
"<elem></elem>";return a.childNodes.length!==1}()&&function(a,b){function c(a){for(var b=-1;++b<e;)a.createElement(d[b])}a.iepp=a.iepp||{};var f=a.iepp,k=f.html5elements||"abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",d=k.split("|"),e=d.length,g=RegExp("(^|\\s)("+k+")","gi"),j=RegExp("<(/*)("+k+")","gi"),h=/^\s*[\{\}]\s*$/,l=RegExp("(^|[^\\n]*?\\s)("+k+")([^\\n]*)({[\\n\\w\\W]*?})","gi"),B=b.createDocumentFragment(),
q=b.documentElement,k=q.firstChild,i=b.createElement("body"),K=b.createElement("style"),O=/print|all/,C;f.getCSS=function(a,b){if(a+""===m)return"";for(var c=-1,d=a.length,k,e=[];++c<d;)k=a[c],k.disabled||(b=k.media||b,O.test(b)&&e.push(f.getCSS(k.imports,b),k.cssText),b="all");return e.join("")};f.parseCSS=function(a){for(var b=[],f;(f=l.exec(a))!=null;)b.push(((h.exec(f[1])?"\n":f[1])+f[2]+f[3]).replace(g,"$1.iepp_$2")+f[4]);return b.join("\n")};f.writeHTML=function(){var a=-1;for(C=C||b.body;++a<
e;)for(var f=b.getElementsByTagName(d[a]),c=f.length,k=-1;++k<c;)f[k].className.indexOf("iepp_")<0&&(f[k].className+=" iepp_"+d[a]);B.appendChild(C);q.appendChild(i);i.className=C.className;i.id=C.id;i.innerHTML=C.innerHTML.replace(j,"<$1font")};f._beforePrint=function(){K.styleSheet.cssText=f.parseCSS(f.getCSS(b.styleSheets,"all"));f.writeHTML()};f.restoreHTML=function(){i.innerHTML="";q.removeChild(i);q.appendChild(C)};f._afterPrint=function(){f.restoreHTML();K.styleSheet.cssText=""};c(b);c(B);
if(!f.disablePP)k.insertBefore(K,k.firstChild),K.media="print",K.className="iepp-printshim",a.attachEvent("onbeforeprint",f._beforePrint),a.attachEvent("onafterprint",f._afterPrint)}(i,e);h._enableHTML5=!0;h._version="1.8pre";h.mq=J;h.isEventSupported=z;n.className=n.className.replace(/\bno-js\b/,"")+" js "+E.join(" ");return h}(this,this.document);
(function(i,e,m){function t(){var a=c;a.loader={load:H,i:0};return a}function H(a,b,c){var d=b=="c"?J:y;o=0;b=b||"j";v(a)?r(d,a,b,this.i++,u,c):(s.splice(this.i++,0,a),s.length==1&&I());return this}function r(a,b,i,h,n,N){function m(){!B&&(!l.readyState||l.readyState=="loaded"||l.readyState=="complete")&&(q.r=B=1,!o&&p(),l.onload=l.onreadystatechange=null,j(function(){D.removeChild(l)},0))}var l=e.createElement(a),B=0,q={t:i,s:b,e:N};l.src=l.data=b;!d&&(l.style.display="none");l.width=l.height="0";
a!="object"&&(l.type=i);l.onload=l.onreadystatechange=m;a=="img"?l.onerror=m:a=="script"&&(l.onerror=function(){q.e=q.r=1;I()});s.splice(h,0,q);D.insertBefore(l,d?null:g);j(function(){B||(D.removeChild(l),q.r=q.e=B=1,p())},c.errorTimeout)}function I(){var a=s.shift();o=1;a?a.t?j(function(){a.t=="c"?h(a):n(a)},0):(a(),p()):o=0}function h(a){var b=e.createElement("link"),d;b.href=a.s;b.rel="stylesheet";b.type="text/css";!a.e&&(E||w)?function M(a){j(function(){if(!d)try{a.sheet.cssRules.length?(d=1,
p()):M(a)}catch(b){b.code==1E3||b.message=="security"||b.message=="denied"?(d=1,j(function(){p()},0)):M(a)}},0)}(b):(b.onload=function(){d||(d=1,j(function(){p()},0))},a.e&&b.onload());j(function(){d||(d=1,p())},c.errorTimeout);!a.e&&g.parentNode.insertBefore(b,g)}function n(a){var b=e.createElement("script"),d;b.src=a.s;b.onreadystatechange=b.onload=function(){!d&&(!b.readyState||b.readyState=="loaded"||b.readyState=="complete")&&(d=1,p(),b.onload=b.onreadystatechange=null)};j(function(){d||(d=1,
p())},c.errorTimeout);a.e?b.onload():g.parentNode.insertBefore(b,g)}function p(){for(var a=1,b=-1;s.length-++b;)if(s[b].s&&!(a=s[b].r))break;a&&I()}var u=e.documentElement,j=i.setTimeout,g=e.getElementsByTagName("script")[0],x={}.toString,s=[],o=0,w="MozAppearance"in u.style,d=w&&!!e.createRange().compareNode,D=d?u:g.parentNode,L=i.opera&&x.call(i.opera)=="[object Opera]",E="webkitAppearance"in u.style,F=E&&"async"in e.createElement("script"),y=w?"object":L||F?"img":"script",J=E?"img":y,z=Array.isArray||
function(a){return x.call(a)=="[object Array]"},v=function(a){return typeof a=="string"},G=function(a){return x.call(a)=="[object Function]"},A=[],a={},b,c;c=function(b){function d(a,b){function c(a){if(v(a))e(a,i,b,0,f);else if(typeof a=="object")for(g in a)a.hasOwnProperty(g)&&e(a[g],i,b,g,f)}var f=!!a.test,h=a.load||a.both,i=a.callback,g;c(f?a.yep:a.nope);c(h);a.complete&&b.load(a.complete)}function e(a,b,d,c,f){var g=i(a),h=g.autoCallback;if(!g.bypass){b&&(b=G(b)?b:b[a]||b[c]||b[a.split("/").pop().split("?")[0]]);
if(g.instead)return g.instead(a,b,d,c,f);d.load(g.url,g.forceCSS||!g.forceJS&&/css$/.test(g.url)?"c":m,g.noexec);(G(b)||G(h))&&d.load(function(){t();b&&b(g.origUrl,f,c);h&&h(g.origUrl,f,c)})}}function i(b){var b=b.split("!"),d=A.length,c=b.pop(),f=b.length,c={url:c,origUrl:c,prefixes:b},e,g;for(g=0;g<f;g++)e=a[b[g]],e&&(c=e(c));for(g=0;g<d;g++)c=A[g](c);return c}var g,h,j=this.yepnope.loader;if(v(b))e(b,0,j,0);else if(z(b))for(g=0;g<b.length;g++)h=b[g],v(h)?e(h,0,j,0):z(h)?c(h):typeof h=="object"&&
d(h,j);else typeof b=="object"&&d(b,j)};c.addPrefix=function(b,c){a[b]=c};c.addFilter=function(a){A.push(a)};c.errorTimeout=1E4;e.readyState==null&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",b=function(){e.removeEventListener("DOMContentLoaded",b,0);e.readyState="complete"},0));i.yepnope=t()})(this,this.document);
